sudo: required
services:
    - docker

before_install:
    - docker build -t sainathpv/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sainathpv/docker-react npm run test
#    - docker run sainathpv/docker-react npm run test -- --coverage ----> Stephen Grider, didn't work

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-386117408010"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

