sudo: required
services:
    - docker

before_install:
    - docker build -t sainathpv/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sainathpv/docker-react npm run test

#    - docker run sainathpv/docker-react npm run test -- --coverage ----> Stephen Grider, didn't work
